In [3]:
import pandas as pd
my_data_set = pd.read_csv('icecreams_sales.csv')
my_data_set

    Temperature (F) Ice Crean Flavor Day of the Week  Sales (in cones)
0                 7        Chocolate          Monday                11
1                 9          Vanilla       Wednesday                27
2                 5       Strawberry          Friday                14
3                 8             Mint         Tuesday                 6
4                 6          Vanilla        Thursday                23
5                10       Strawberry       Wednesday                18
6                 9        Chocolate          Friday                 4
7                 7             Mint          Monday                15
8                 5       Strawberry         Tuesday                28
9                 7        Chocolate        Thursday                25
10                5          Vanilla          Monday                12